//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bibliothèque
{
    using System;
    using System.Collections.Generic;
    
    public partial class LivrePerdu
    {
        public int IdLivre { get; set; }
        public System.DateTime datPerdu { get; set; }
    
        public virtual Livre Livre { get; set; }
    }
}
