//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bibliothèque
{
    using System;
    using System.Collections.Generic;
    
    public partial class Livre
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Livre()
        {
            this.Emprinte = new HashSet<Emprinte>();
        }
    
        public int IdLivre { get; set; }
        public Nullable<int> IdOuvrage { get; set; }
        public string IspnLivre { get; set; }
        public string EtatLivre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emprinte> Emprinte { get; set; }
        public virtual Ouvrage Ouvrage { get; set; }
        public virtual LivrePerdu LivrePerdu { get; set; }
    }
}
