//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bibliothèque
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BibliothèqueEntities : DbContext
    {
        public BibliothèqueEntities()
            : base("name=BibliothèqueEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Emprinte> Emprinte { get; set; }
        public virtual DbSet<Filiere> Filiere { get; set; }
        public virtual DbSet<Groupe> Groupe { get; set; }
        public virtual DbSet<Livre> Livre { get; set; }
        public virtual DbSet<Ouvrage> Ouvrage { get; set; }
        public virtual DbSet<Secteur> Secteur { get; set; }
        public virtual DbSet<Stagiaire> Stagiaire { get; set; }
        public virtual DbSet<Theme> Theme { get; set; }
        public virtual DbSet<LivrePerdu> LivrePerdus { get; set; }
    }
}
