//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bibliothèque
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ouvrage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ouvrage()
        {
            this.Livre = new HashSet<Livre>();
        }
    
        public int IdOuvrage { get; set; }
        public Nullable<int> IdSecteur { get; set; }
        public Nullable<int> IdTheme { get; set; }
        public string TitreOuvrage { get; set; }
        public Nullable<double> PrixOuvrage { get; set; }
        public string LieuOuvrage { get; set; }
        public string AuteurOuvrage { get; set; }
        public string EditeurOuvrage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Livre> Livre { get; set; }
        public virtual Secteur Secteur { get; set; }
        public virtual Theme Theme { get; set; }
    }
}
